'use strict';
const $=id=>document.getElementById(id), months=Array.from({length:12},(_,i)=>i+1);
const example={t:[-2,0,5,11,17,22,25,26,21,14,7,0],p:[20,25,45,70,95,140,290,270,140,55,45,25]};
$('rows').innerHTML=months.map((m,i)=>`<tr><td>${m}월</td><td><input type="number" step="0.1" data-i="${i}" data-kind="t" aria-label="${m}월 기온"></td><td><input type="number" min="0" step="0.1" data-i="${i}" data-kind="p" aria-label="${m}월 강수량"></td></tr>`).join('');
$('month').innerHTML=months.map((m,i)=>`<option value="${i}">${m}월</option>`).join('');
const cell=(i,k)=>document.querySelector(`[data-i="${i}"][data-kind="${k}"]`);
function values(){return Object.fromEntries(['t','p'].map(k=>[k,months.map((_,i)=>cell(i,k).value.trim()===''?null:Number(cell(i,k).value))]));}
function settings(){return Object.fromEntries(['tmin','tmax','tstep','pmax','pstep'].map(k=>[k,$(k).value.trim()===''?NaN:Number($(k).value)]));}
function validate(s,d){if(!Object.values(s).every(Number.isFinite)||s.tmax<=s.tmin||s.pmax<=0||s.tstep<=0||s.pstep<=0)return '축 범위와 눈금 간격을 확인해 주세요.';if((s.tmax-s.tmin)/s.tstep>30||s.pmax/s.pstep>30)return '눈금이 너무 촘촘합니다. 각 축의 눈금 수를 30개 이하로 설정해 주세요.';if([...d.t,...d.p].some(v=>v===null||!Number.isFinite(v)))return '12개월의 기온과 강수량을 모두 입력해 주세요.';if(d.p.some(v=>v<0))return '강수량은 0 이상이어야 합니다.';if(d.t.some(v=>v<s.tmin||v>s.tmax)||d.p.some(v=>v>s.pmax))return '눈금 범위를 벗어난 값이 있습니다. 축 범위를 넓혀 주세요.';return '';}
const fmt=v=>Number(v.toFixed(2)).toString().replace('-','−');
const escapeXML=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function graph(s,d){const x=105,y=86,w=322,h=388,dx=w/12,ty=v=>y+h-(v-s.tmin)/(s.tmax-s.tmin)*h,py=v=>y+h-v/s.pmax*h;let out=`<svg xmlns="http://www.w3.org/2000/svg" width="540" height="540" viewBox="0 0 540 540" role="img" aria-label="월별 기온과 강수량 그래프"><rect width="540" height="540" fill="white"/><g font-family="Arial,Malgun Gothic,sans-serif" font-size="42" font-weight="400">`;
for(let i=0;i<=Math.floor((s.tmax-s.tmin)/s.tstep+1e-8);i++){let v=s.tmin+i*s.tstep,Y=ty(v);out+=`<line x1="${x}" y1="${Y}" x2="${x+w}" y2="${Y}" stroke="#aaa" stroke-width="1.8" ${Math.abs(v)<1e-9?'':'stroke-dasharray="2 4"'}/><text x="${x-17}" y="${Y}" dy=".34em" text-anchor="end" fill="#ff0051">${fmt(v)}</text>`;}
for(let i=0;i<=Math.floor(s.pmax/s.pstep+1e-8);i++){let v=i*s.pstep;out+=`<text x="${x+w+17}" y="${py(v)}" dy=".34em" fill="#009ee8">${fmt(v)}</text>`;}
out+=`<defs><clipPath id="plot"><rect x="${x}" y="${y-4}" width="${w}" height="${h+8}"/></clipPath></defs><g clip-path="url(#plot)">`;
d.p.forEach((v,i)=>{if(v!==null&&Number.isFinite(v)&&v>=0)out+=`<rect x="${x+dx*(i+.5)-dx*.33}" y="${py(v)}" width="${dx*.66}" height="${Math.max(0,y+h-py(v))}" fill="#0075b9"/>`;});
let path='';d.t.forEach((v,i)=>{if(v!==null&&Number.isFinite(v)){path+=`${i===0||d.t[i-1]===null?'M':'L'}${x+dx*(i+.5)},${ty(v)} `;}});out+=`<path d="${path}" fill="none" stroke="#ff101b" stroke-width="3" stroke-linejoin="round"/>`;
d.t.forEach((v,i)=>{if(v!==null&&Number.isFinite(v))out+=`<circle cx="${x+dx*(i+.5)}" cy="${ty(v)}" r="5.4" fill="white" stroke="#ff101b" stroke-width="2.2"/>`;});
out+=`</g><path d="M${x},${y}V${y+h}H${x+w}V${y}" fill="none" stroke="#777" stroke-width="2"/><text x="${x-17}" y="45" text-anchor="end" font-size="34" fill="#ff0051">(℃)</text><text x="${x+w+17}" y="45" fill="#009ee8" font-size="34">(mm)</text>`;
[0,2,4,6,8,10].forEach(i=>out+=`<text x="${x+dx*(i+.5)}" y="530" fill="#444" text-anchor="middle">${i+1}</text>`);out+=`<text x="${x+w-2}" y="530" fill="#444" font-size="36">(월)</text></g></svg>`;const title=$('showTitle').checked&&$('chartTitle').value.trim(),sourceText=$('showSource').checked&&$('chartSource').value.trim();if(title||sourceText){
const wrapText=text=>{const lines=[];let line='',width=0;for(const c of text){const advance=/[\u1100-\u11ff\u3000-\uffff]/.test(c)?42:/[il.,' :;!|]/.test(c)?12:24;if(width+advance>490&&line){lines.push(line);line='';width=0;}line+=c;width+=advance;}if(line)lines.push(line);return lines;};
const titleLines=title?wrapText(title):[],sourceLines=sourceText?wrapText(sourceText):[];
const top=titleLines.length?titleLines.length*52+14:0;
const bottom=sourceLines.length?30+sourceLines.length*52+10:0;
const height=540+top+bottom;
const textStyle='font-family="Arial,Malgun Gothic,sans-serif" font-size="42" font-weight="400"';
const titleMarkup=titleLines.map((line,i)=>`<text x="270" y="${44+i*52}" text-anchor="middle" ${textStyle} fill="#333">${escapeXML(line)}</text>`).join('');
const sourceMarkup=sourceLines.map((line,i)=>`<text x="523" y="${top+540+30+42+i*52}" text-anchor="end" ${textStyle} fill="#666">${escapeXML(line)}</text>`).join('');
out=out.replace('viewBox="0 0 540 540"',`viewBox="0 0 540 ${height}"`).replace('height="540" viewBox',`height="${height}" viewBox`).replace('<rect width="540" height="540" fill="white"/>',`<rect width="540" height="${height}" fill="white"/><g transform="translate(0 ${top})">`).replace('</svg>','</g>'+titleMarkup+sourceMarkup+'</svg>');
}return out;}
let currentSVG='';
function render(){const s=settings(),d=values(),error=validate(s,d);$('error').textContent=error;['png','svg','csv'].forEach(k=>$(k).disabled=!!error);if(!Object.values(s).every(Number.isFinite)||s.tmax<=s.tmin||s.pmax<=0||s.tstep<=0||s.pstep<=0||(s.tmax-s.tmin)/s.tstep>30||s.pmax/s.pstep>30)return;currentSVG=graph(s,d);$('chart').innerHTML=currentSVG;}
function put(d){months.forEach((_,i)=>['t','p'].forEach(k=>cell(i,k).value=d[k][i]??''));render();}
$('rows').addEventListener('input',render);['tmin','tmax','tstep','pmax','pstep'].forEach(k=>$(k).addEventListener('input',render));
$('sample').onclick=()=>{setPreset('basic');put(example);};$('clear').onclick=()=>{if(confirm('입력한 24개 값을 모두 비울까요?'))put({t:Array(12).fill(null),p:Array(12).fill(null)});};
function setPreset(p){const a=p==='wide'?[-30,40,10,700,100]:[-10,30,5,400,50];['tmin','tmax','tstep','pmax','pstep'].forEach((k,i)=>$(k).value=a[i]);render();}
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>setPreset(b.dataset.preset));
$('rows').addEventListener('paste',e=>{if(!e.target.matches('input'))return;const text=e.clipboardData.getData('text').trim();if(!/[\t\n,]/.test(text))return;e.preventDefault();const rows=text.split(/\r?\n/).map(r=>r.split(/[\t,]/).map(x=>x.trim()));const start=+e.target.dataset.i,kind=e.target.dataset.kind;let updates=[];
if(rows.length===1&&rows[0].length>2){rows[0].forEach((v,j)=>updates.push([start+j,kind,v]));}else{rows.forEach((r,j)=>r.forEach((v,k)=>updates.push([start+j,k===0?kind:'p',v])));if(rows.some(r=>r.length>(kind==='t'?2:1))){alert('기온·강수량 2열 또는 한 항목의 12개 숫자만 복사해 주세요.');return;}}
if(updates.some(([i,k,v])=>i>11||v===''||!Number.isFinite(Number(v))||(k==='p'&&Number(v)<0))){alert('붙여넣을 범위와 숫자를 확인해 주세요. 최대 12개월, 강수량은 0 이상입니다.');return;}updates.forEach(([i,k,v])=>cell(i,k).value=v);render();});
function filename(ext){return ($('filename').value.trim().replace(/[\\/:*?"<>|]/g,'_')||'기후그래프')+'.'+ext;}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);}
$('svg').onclick=()=>download(new Blob([currentSVG],{type:'image/svg+xml;charset=utf-8'}),filename('svg'));
$('csv').onclick=()=>{const d=values();download(new Blob(['\ufeff월,기온(℃),강수량(mm)\r\n'+months.map((m,i)=>`${m},${d.t[i]},${d.p[i]}`).join('\r\n')],{type:'text/csv;charset=utf-8'}),filename('csv'));};
$('png').onclick=async()=>{const button=$('png');button.disabled=true;try{const image=new Image(),url=URL.createObjectURL(new Blob([currentSVG],{type:'image/svg+xml'}));try{await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url;});const canvas=document.createElement('canvas');canvas.width=Number($('size').value);canvas.height=Math.round(canvas.width*(Number(currentSVG.match(/viewBox="0 0 540 ([\d.]+)"/)[1])/540));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error();download(blob,filename('png'));}finally{URL.revokeObjectURL(url);}}catch{alert('PNG 저장에 실패했습니다. 더 작은 크기로 다시 시도해 주세요.');}finally{render();}};
// All image processing stays in this browser. No network requests or AI services.
const canvas=$('source'),ctx=canvas.getContext('2d');let source=null,raw=null,box=null,anchor=null,phase='region',estimate={t:Array(12).fill(null),p:Array(12).fill(null)};
function sourceSettings(){const keys=['srcTop','srcBottom','srcPtop','srcPbottom'],v=keys.map(k=>$(k).value.trim()===''?NaN:Number($(k).value));if(!v.every(Number.isFinite)||v[0]<=v[1]||v[2]<=v[3]||v[3]<0){alert('원본의 상단 눈금은 하단보다 커야 하며, 강수량은 0 이상이어야 합니다.');return null;}return {top:v[0],bottom:v[1],ptop:v[2],pbottom:v[3]};}
function numericAt(y,k,s){const f=(box.b-y)/(box.b-box.t);return Math.round((k==='t'?s.bottom+f*(s.top-s.bottom):s.pbottom+f*(s.ptop-s.pbottom))*10)/10;}
function pixelAt(v,k,s){return box.b-(k==='t'?(v-s.bottom)/(s.top-s.bottom):(v-s.pbottom)/(s.ptop-s.pbottom))*(box.b-box.t);}
function paint(){if(!source)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(source,0,0,canvas.width,canvas.height);if(box){ctx.strokeStyle='#8055e7';ctx.lineWidth=Math.max(1,canvas.width/450);ctx.setLineDash([5,4]);ctx.strokeRect(box.l,box.t,box.r-box.l,box.b-box.t);ctx.setLineDash([]);const s={top:+$('srcTop').value,bottom:+$('srcBottom').value,ptop:+$('srcPtop').value,pbottom:+$('srcPbottom').value};for(let i=0;i<12;i++){const x=box.l+(i+.5)*(box.r-box.l)/12;['t','p'].forEach(k=>{const v=estimate[k][i];if(v===null)return;const y=pixelAt(v,k,s);if(!Number.isFinite(y))return;ctx.beginPath();ctx.strokeStyle=k==='t'?'#aa00cc':'#00a46c';ctx.arc(x,y,Math.max(2,canvas.width/160),0,Math.PI*2);ctx.stroke();});}}if(anchor){ctx.fillStyle='#8055e7';ctx.beginPath();ctx.arc(anchor.x,anchor.y,Math.max(2,canvas.width/160),0,Math.PI*2);ctx.fill();}}
function showEstimates(){let html='<table><thead><tr><th>월</th>'+months.map(m=>`<th>${m}</th>`).join('')+'</tr></thead><tbody>';['t','p'].forEach(k=>html+='<tr><th>'+(k==='t'?'℃':'mm')+'</th>'+estimate[k].map(v=>`<td>${v??'—'}</td>`).join('')+'</tr>');$('estimates').innerHTML=html+'</tbody></table>';$('apply').disabled=[...estimate.t,...estimate.p].some(v=>v===null);showSimple();paint();}
function resetRegion(){box=null;anchor=null;phase='region';estimate={t:Array(12).fill(null),p:Array(12).fill(null)};$('guide').textContent='그래프 안쪽 왼쪽 위 모서리를 클릭하세요.';$('detect').disabled=true;$('manual').disabled=true;showEstimates();}
let imageSequence=0;
$('upload').onchange=async e=>{const file=e.target.files[0];if(!file)return;const token=++imageSequence;if(file.size>20*1024*1024){alert('20MB 이하의 이미지를 선택해 주세요.');return;}const url=URL.createObjectURL(file),img=new Image();try{await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url;});if(token!==imageSequence)return;const scale=Math.min(1,1600/Math.max(img.width,img.height));canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);source=img;ctx.drawImage(img,0,0,canvas.width,canvas.height);raw=ctx.getImageData(0,0,canvas.width,canvas.height);$('extractBody').hidden=false;resetRegion();autoExtract();}catch{alert('이미지를 읽을 수 없습니다. PNG 또는 JPG로 다시 선택해 주세요.');}finally{URL.revokeObjectURL(url);}};
$('region').onclick=resetRegion;
canvas.addEventListener('click',e=>{if(!source)return;const r=canvas.getBoundingClientRect(),x=Math.max(0,Math.min(canvas.width-1,(e.clientX-r.left)*canvas.width/r.width)),y=Math.max(0,Math.min(canvas.height-1,(e.clientY-r.top)*canvas.height/r.height));if(phase==='region'){if(!anchor){anchor={x,y};$('guide').textContent='이제 그래프 안쪽 오른쪽 아래 모서리를 클릭하세요.';paint();}else{if(x-anchor.x<24||y-anchor.y<24){$('guide').textContent='첫 점보다 오른쪽 아래에, 충분히 큰 영역을 지정해 주세요.';return;}box={l:anchor.x,t:anchor.y,r:x,b:y};anchor=null;phase='ready';$('detect').disabled=false;$('manual').disabled=false;$('guide').textContent='원본 눈금을 확인한 뒤 색상을 찾거나 직접 클릭해서 값을 지정하세요.';paint();}}else if(phase==='manual'&&box){if(x<box.l||x>box.r||y<box.t||y>box.b)return;const s=sourceSettings();if(!s)return;const i=+$('month').value,k=$('mode').value;estimate[k][i]=numericAt(y,k,s);$('month').value=(i+1)%12;showEstimates();$('guide').textContent=`${i+1}월 ${k==='t'?'기온':'강수량'} 보정 완료. 다음은 ${+$('month').value+1}월입니다.`;}});
$('manual').onclick=()=>{if(!box)return;if(!sourceSettings())return;phase='manual';$('guide').textContent='선택한 월의 기온 선 중심 또는 강수량 막대 상단을 클릭하세요.';};
['srcTop','srcBottom','srcPtop','srcPbottom'].forEach(k=>$(k).addEventListener('input',()=>{estimate={t:Array(12).fill(null),p:Array(12).fill(null)};showEstimates();$('guide').textContent='원본 눈금이 바뀌었습니다. 다시 추출하거나 클릭 보정해 주세요.';}));
$('detect').onclick=()=>{if(!box)return;const s=sourceSettings();if(!s)return;const width=canvas.width,dx=(box.r-box.l)/12;estimate={t:[],p:[]};for(let i=0;i<12;i++){const center=box.l+dx*(i+.5),left=Math.max(0,Math.floor(center-dx*.24)),right=Math.min(width-1,Math.ceil(center+dx*.24)),red=[],blue=[];for(let y=Math.ceil(box.t);y<Math.floor(box.b);y++){let rc=0,bc=0;for(let x=left;x<=right;x++){const off=(y*width+x)*4,[r,g,b,a]=raw.data.subarray(off,off+4);if(a<100)continue;if(r>140&&r>g*1.35&&r>b*1.25)rc++;if(b>85&&b>r*1.3&&g>r*1.15)bc++;}if(rc>0)red.push(y);if(bc>=Math.max(1,(right-left+1)*.3))blue.push(y);}estimate.t.push(red.length?numericAt(red[Math.floor(red.length/2)],'t',s):null);estimate.p.push(blue.length?numericAt(blue[0],'p',s):null);}phase='ready';showEstimates();const missing=[...estimate.t,...estimate.p].filter(v=>v===null).length;$('guide').textContent=`색상 추출 완료. ${missing?missing+'개 값은 직접 클릭 보정이 필요합니다.':'원본과 대조하고 필요하면 클릭 보정해 주세요.'}`;};
$('apply').onclick=()=>{if([...estimate.t,...estimate.p].some(v=>v===null))return;const d=values();if([...d.t,...d.p].some(v=>v!==null)&&!confirm('입력표의 기존 값을 추정값으로 바꿀까요?'))return;put(estimate);$('guide').textContent='입력표에 적용했습니다. 최종 값과 출력 눈금 범위를 확인해 주세요.';$('rows').scrollIntoView({behavior:'smooth',block:'start'});};
put({t:Array(12).fill(null),p:Array(12).fill(null)});

$('reset').onclick=()=>{if(confirm('전체 화면을 초기화할까요? 입력한 내용은 지워집니다.'))location.reload();};
['showTitle','showSource','chartTitle','chartSource'].forEach(id=>$(id).addEventListener('input',render));
$('template').onclick=()=>download(new Blob(['\ufeff월,기온(℃),강수량(mm)\r\n'+months.map(m=>`${m},,`).join('\r\n')],{type:'text/csv;charset=utf-8'}),'기후그래프_입력양식.csv');
function parseCSV(text){let rows=[],row=[],field='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){field+='"';i++;}else quote=!quote;}else if(c===','&&!quote){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some(v=>v.trim()))rows.push(row);row=[];field='';}else field+=c;}if(quote)throw Error('따옴표가 닫히지 않았습니다.');row.push(field);if(row.some(v=>v.trim()))rows.push(row);if(rows.length&&rows[0][0].replace(/^\ufeff/,'').trim()==='월')rows.shift();if(rows.length!==12)throw Error('1~12월의 데이터 12행이 필요합니다.');const result={t:[],p:[]},seen=new Set();for(const r of rows){if(r.length!==3)throw Error('월, 기온, 강수량의 3열 양식을 사용해 주세요.');const [m,t,p]=r.map(v=>v.replace(/^\ufeff/,'').trim());const month=Number(m);if(!Number.isInteger(month)||month<1||month>12||seen.has(month))throw Error('월은 1~12월을 중복 없이 입력해 주세요.');if(t===''||p===''||!Number.isFinite(Number(t))||!Number.isFinite(Number(p))||Number(p)<0)throw Error(month+'월의 기온·강수량을 확인해 주세요.');seen.add(month);result.t[month-1]=Number(t);result.p[month-1]=Number(p);}return result;}
$('dataUpload').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>1024*1024)throw Error('1MB 이하의 CSV를 선택해 주세요.');const bytes=await f.arrayBuffer();let text=new TextDecoder('utf-8').decode(bytes);if(text.includes('�'))text=new TextDecoder('euc-kr').decode(bytes);const d=parseCSV(text);if([...values().t,...values().p].some(v=>v!==null)&&!confirm('입력한 값을 업로드한 데이터로 바꿀까요?'))return;put(d);}catch(err){alert(err.message);}finally{e.target.value='';}};
function showSimple(){ $('simpleEstimates').innerHTML='<table><thead><tr><th>월</th><th>기온 (℃)</th><th>강수량 (㎜)</th></tr></thead><tbody>'+months.map((m,i)=>`<tr><td>${m}월</td>${['t','p'].map(k=>`<td><input type="number" step="0.1" ${k==='p'?'min="0"':''} data-est="${k}" data-month="${i}" aria-label="추정 ${m}월 ${k==='t'?'기온':'강수량'}" value="${estimate[k][i]??''}" placeholder="확인 필요"></td>`).join('')}</tr>`).join('')+'</tbody></table>';$('simpleApply').disabled=[...estimate.t,...estimate.p].some(v=>v===null||!Number.isFinite(v))||estimate.p.some(v=>v<0);}
$('simpleEstimates').addEventListener('input',e=>{if(!e.target.matches('[data-est]'))return;const v=e.target.value.trim();estimate[e.target.dataset.est][+e.target.dataset.month]=v===''?null:Number(v);$('simpleApply').disabled=[...estimate.t,...estimate.p].some(v=>v===null||!Number.isFinite(v))||estimate.p.some(v=>v<0);paint();});
$('simpleApply').onclick=()=>{const s=sourceSettings();if(!s)return;$('tmin').value=s.bottom;$('tmax').value=s.top;$('tstep').value=(s.top-s.bottom)<=40?5:10;$('pmax').value=s.ptop;$('pstep').value=s.ptop<=400?50:100;$('apply').onclick();};
function applySourcePreset(wide){$('srcTop').value=wide?40:30;$('srcBottom').value=wide?-30:-10;$('srcPtop').value=wide?700:400;$('srcPbottom').value=0;if(box){$('detect').onclick();$('autoStatus').textContent='선택한 원본 눈금으로 다시 추정했습니다. 값을 확인해 주세요.';}}
$('autoBasic').onclick=()=>applySourcePreset(false);$('autoWide').onclick=()=>applySourcePreset(true);
function autoExtract(){const W=raw.width,H=raw.height,gray=(x,y)=>{const j=(y*W+x)*4,r=raw.data[j],g=raw.data[j+1],b=raw.data[j+2];return raw.data[j+3]>100&&Math.max(r,g,b)-Math.min(r,g,b)<28&&r<225;};
// Detect long neutral vertical axes; do not treat colored bars as axes.
const runs=[];for(let x=1;x<W-1;x++){let start=-1,last=-1;for(let y=0;y<H;y++){if(gray(x,y)){if(start<0)start=y;last=y;}else if(start>=0&&y-last>2){if(last-start>H*.32)runs.push({x,t:start,b:last,length:last-start});start=-1;}}if(start>=0&&last-start>H*.32)runs.push({x,t:start,b:last,length:last-start});}
let best=null;for(const a of runs)for(const b of runs){if(b.x-a.x<W*.3||Math.abs(a.t-b.t)>H*.08||Math.abs(a.b-b.b)>H*.08)continue;const score=Math.min(a.length,b.length)+(b.x-a.x)*.25;if(!best||score>best.score)best={l:a.x,r:b.x,t:Math.max(a.t,b.t),b:Math.min(a.b,b.b),score};}
if(!best){$('autoStatus').textContent='그래프 영역을 찾기 어렵습니다. 세부 보정에서 영역을 지정하거나 월별 값을 직접 입력해 주세요.';$('advanced').open=true;return;}
box=best;anchor=null;phase='ready';$('detect').disabled=false;$('manual').disabled=false;
const lines=[];for(let y=Math.ceil(box.t);y<=box.b;y++){let n=0;for(let x=Math.ceil(box.l+3);x<box.r-3;x++)if(gray(x,y))n++;if(n/(box.r-box.l-6)>.17){if(!lines.length||y-lines[lines.length-1]>2)lines.push(y);}}
const gaps=lines.slice(1).map((v,i)=>v-lines[i]).filter(v=>v>3).sort((a,b)=>a-b);const interval=gaps.length?gaps[Math.floor(gaps.length/2)]:0;const wide=interval>0&&Math.round((box.b-box.t)/interval)===7;applySourcePreset(wide);$('autoStatus').textContent=`자동 추정 완료 · 원본 눈금은 ${wide?'−30~40℃ / 700㎜':'−10~30℃ / 400㎜'}로 가정했습니다. 원본과 다르면 위 버튼 또는 세부 보정에서 바꿔 주세요. 빈칸은 직접 입력해 주세요.`;
}
